### PR TITLE
PHP 8.0 and phpunit/phpunit:^9.5

### PR DESCRIPTION
**Pull request by ssmarco**
Adding PHP 8 support and update PHPUnit to ^9.5

### CODE REVIEW

**Comment by ssmarco** [comment]
Hi @madmatt @chillu 
Can you have a look at my PR pls :)

**Comment by madmatt** [comment]
Looks great, thanks @ssmarco! Thanks for finally getting rid of the accidental `vendor` directory too, I could have sworn I did that in #3 but who knows what happened there!

**Comment by madmatt** [comment]
Hey @ssmarco, sorry for the GitHub notification spam, I've just created actual GitHub releases for the `1.0.0` and `2.0.0` tags (these appear to actually be the same commit, so who knows what I was thinking back then.

I've also just created a new 3.0.0 tag and release which you can now use directly in your `composer.json`: https://github.com/chillu/fakedatabase/releases/tag/3.0.0

Thanks again for doing this!

**Comment by ssmarco** [comment]
Thanks @madmatt Hope you are well :)

**Comment by madmatt** [comment]
You too @ssmarco! :)

**Pull request merged**
